apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: frontend-container
        image: beirdinhos/frontend:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 80

        env:
        - name: NODE_ENV
          value: "production"
        - name: API_GATEWAY_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: API_GATEWAY_URL
