apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-ingestion-deployment
  labels:
    app: api-ingestion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-ingestion
  template:
    metadata:
      labels:
        app: api-ingestion
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox:1.36
        command:
        - sh
        - -c
        - |
          echo "Waiting for postgres to be ready..."
          until nc -z -w 2 postgis.default.svc.cluster.local 5432 2>/dev/null; do
            echo "Postgres not ready, waiting..."
            sleep 2
          done
          echo "Postgres is ready!"
        resources:
          requests:
            memory: "16Mi"
            cpu: "10m"
          limits:
            memory: "32Mi"
            cpu: "50m"

      - name: wait-for-redis
        image: busybox:1.36
        command:
        - sh
        - -c
        - |
          echo "Waiting for redis to be ready..."
          until nc -z -w 2 redis.default.svc.cluster.local 6379 2>/dev/null; do
            echo "Redis not ready, waiting..."
            sleep 2
          done
          echo "Redis is ready!"
        resources:
          requests:
            memory: "16Mi"
            cpu: "10m"
          limits:
            memory: "32Mi"
            cpu: "50m"
      - name: wait-for-capteur
        image: busybox:1.36
        command:
        - sh
        - -c
        - |
          echo "Waiting for api-capteur to be ready..."
          until nc -z -w 2 api-capteur-service.default.svc.cluster.local 3000 2>/dev/null; do
            echo "API Capteur not ready, waiting..."
            sleep 2
          done
          echo "API Capteur is ready!"
        resources:
          requests:
            memory: "16Mi"
            cpu: "10m"
          limits:
            memory: "32Mi"
            cpu: "50m"
      containers:
      - name: api-ingestion-container
        image: 127.0.0.1:5000/api-ingestion:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 3001

        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"

        env:
        - name: NODE_ENV
          value: "development"
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: api-ingestion-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: api-ingestion-config
              key: DB_PORT
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: api-ingestion-config
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: api-ingestion-config
              key: DB_PASSWORD
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: api-ingestion-config
              key: DB_DATABASE
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: api-ingestion-config
              key: PORT
        - name: KAFKA_BROKER
          valueFrom:
            configMapKeyRef:
              name: api-ingestion-config
              key: KAFKA_BROKER
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: api-ingestion-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: api-ingestion-config
              key: REDIS_PORT
        - name: CAPTEUR_SERVICE_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: api-ingestion-config
              key: CAPTEUR_SERVICE_BASE_URL
