apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
spec:
  serviceName: "zookeeper"
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: clean-zookeeper-data
        image: busybox:1.36
        command: ["/bin/sh", "-c", "echo 'Cleaning up /var/lib/zookeeper/data/*'; rm -rf /var/lib/zookeeper/data/*"]
        volumeMounts:
        - name: zookeeper-data
          mountPath: /var/lib/zookeeper/data
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2181
          name: client
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        volumeMounts:
        - name: zookeeper-data
          mountPath: /var/lib/zookeeper/data
  volumeClaimTemplates:
  - metadata:
      name: zookeeper-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 2Gi
