apiVersion: v1
kind: Secret
metadata:
  name: postgis-secret
type: Opaque
stringData:
  # Remplacer par un mot de passe fort
  POSTGRES_PASSWORD: "monSuperMotDePasse"
  # Mot de passe pour l'utilisateur root de la base projet_simon
  ROOT_PASSWORD: "root"
