apiVersion: v1
kind: Service
metadata:
  name: api-gateway-client-service
spec:
  selector:
    app: api-gateway-client
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
