apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-ingestion-deployment
  labels:
    app: api-ingestion
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-ingestion
  template:
    metadata:
      labels:
        app: api-ingestion
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox:1.36
        command:
        - sh
        - -c
        - |
          echo "Waiting for postgres to be ready..."
          until nc -z -w 2 postgis.default.svc.cluster.local 5432 2>/dev/null; do
            echo "Postgres not ready, waiting..."
            sleep 2
          done
          echo "Postgres is ready!"
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: api-ingestion-container
        image: beirdinhos/api-ingestion:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 3001

        env:
        - name: NODE_ENV
          value: "production"
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: api-ingestion-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: api-ingestion-config
              key: DB_PORT
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: api-ingestion-config
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-credentials
              key: DB_PASSWORD
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: api-ingestion-config
              key: DB_DATABASE
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: api-ingestion-config
              key: PORT
